#sudo: true
#before_script:
#  - sudo apt-get update -q
#  - sudo apt-get install gfortran liblapack-dev gcc
#  - sudo apt-get install graphviz

sudo: false

addons:
  apt:
    packages:
    - zlib1g-dev
    - libgmp3-dev
    - gfortran
    - gcc
    - liblapack-dev
    - graphviz

cache:
  directories:
  - $HOME/.opam/

language: python
python:
    - "2.6"

script: 
  - ./configure  --production ./config/travis.cfg
  - source ./quantum_package.rc ; qp_module.py install Full_CI Full_CI_ZMQ Hartree_Fock CAS_SD_ZMQ mrcepa0 All_singles
  - source ./quantum_package.rc ; ninja
  - source ./quantum_package.rc ; cd ocaml ; make ; cd -
  - source ./quantum_package.rc ; cd tests ; ./run_tests.sh -v
